In [1]:
#You can read the results of a SQL query into a Pandas Dataframe using the read_sql_query function.
import pandas as pd
import sqlite3
import math

In [2]:
conn = sqlite3.connect("factbook.db")
cur  = conn.cursor()

In [3]:
sql = "select * from facts;"
facts = pd.read_sql_query(sql,conn)
facts.dropna(axis=0)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate,created_at,updated_at
0,1,af,Afghanistan,652230.0,652230.0,0.0,32564342.0,2.32,38.57,13.89,1.51,2015-11-01 13:19:49.461734,2015-11-01 13:19:49.461734
1,2,al,Albania,28748.0,27398.0,1350.0,3029278.0,0.30,12.92,6.58,3.30,2015-11-01 13:19:54.431082,2015-11-01 13:19:54.431082
2,3,ag,Algeria,2381741.0,2381741.0,0.0,39542166.0,1.84,23.67,4.31,0.92,2015-11-01 13:19:59.961286,2015-11-01 13:19:59.961286
3,4,an,Andorra,468.0,468.0,0.0,85580.0,0.12,8.13,6.96,0.00,2015-11-01 13:20:03.659945,2015-11-01 13:20:03.659945
4,5,ao,Angola,1246700.0,1246700.0,0.0,19625353.0,2.78,38.78,11.49,0.46,2015-11-01 13:20:08.625072,2015-11-01 13:20:08.625072
5,6,ac,Antigua and Barbuda,442.0,442.0,0.0,92436.0,1.24,15.85,5.69,2.21,2015-11-01 13:20:13.049627,2015-11-01 13:20:13.049627
6,7,ar,Argentina,2780400.0,2736690.0,43710.0,43431886.0,0.93,16.64,7.33,0.00,2015-11-01 13:20:18.233063,2015-11-01 13:20:18.233063
7,8,am,Armenia,29743.0,28203.0,1540.0,3056382.0,0.15,13.61,9.34,5.80,2015-11-01 13:20:23.048753,2015-11-01 13:20:23.048753
8,9,as,Australia,7741220.0,7682300.0,58920.0,22751014.0,1.07,12.15,7.14,5.65,2015-11-01 13:20:28.186341,2015-11-01 13:20:28.186341
9,10,au,Austria,83871.0,82445.0,1426.0,8665550.0,0.55,9.41,9.42,5.56,2015-11-01 13:20:33.093597,2015-11-01 13:20:33.093597
10,11,aj,Azerbaijan,86600.0,82629.0,3971.0,9780780.0,0.96,16.64,7.07,0.00,2015-11-01 13:20:38.210262,2015-11-01 13:20:38.210262
11,12,bf,"Bahamas, The",13880.0,10010.0,3870.0,324597.0,0.85,15.50,7.05,0.00,2015-11-01 13:20:42.754219,2015-11-01 13:20:42.754219
12,13,ba,Bahrain,760.0,760.0,0.0,1346613.0,2.41,13.66,2.69,13.09,2015-11-01 13:20:47.686896,2015-11-01 13:20:47.686896
13,14,bg,Bangladesh,148460.0,130170.0,18290.0,168957745.0,1.60,21.14,5.61,0.46,2015-11-01 13:20:52.753843,2015-11-01 13:20:52.753843
14,15,bb,Barbados,430.0,430.0,0.0,290604.0,0.31,11.87,8.44,0.30,2015-11-01 13:20:57.219984,2015-11-01 13:20:57.219984
15,16,bo,Belarus,207600.0,202900.0,4700.0,9589689.0,0.20,10.70,13.36,0.70,2015-11-01 13:21:02.382438,2015-11-01 13:21:02.382438
16,17,be,Belgium,30528.0,30278.0,250.0,11323973.0,0.76,11.41,9.63,5.87,2015-11-01 13:21:07.317024,2015-11-01 13:21:07.317024
17,18,bh,Belize,22966.0,22806.0,160.0,347369.0,1.87,24.68,5.97,0.00,2015-11-01 13:21:12.255851,2015-11-01 13:21:12.255851
18,19,bn,Benin,112622.0,110622.0,2000.0,10448647.0,2.78,36.02,8.21,0.00,2015-11-01 13:21:17.437291,2015-11-01 13:21:17.437291
19,20,bt,Bhutan,38394.0,38394.0,0.0,741919.0,1.11,17.78,6.69,0.00,2015-11-01 13:21:21.942736,2015-11-01 13:21:21.942736
20,21,bl,Bolivia,1098581.0,1083301.0,15280.0,10800882.0,1.56,22.76,6.52,0.62,2015-11-01 13:21:27.041970,2015-11-01 13:21:27.041970
21,22,bk,Bosnia and Herzegovina,51197.0,51187.0,10.0,3867055.0,0.13,8.87,9.75,0.38,2015-11-01 13:21:32.191346,2015-11-01 13:21:32.191346
22,23,bc,Botswana,581730.0,566730.0,15000.0,2182719.0,1.21,20.96,13.39,4.56,2015-11-01 13:21:36.883097,2015-11-01 13:21:36.883097
23,24,br,Brazil,8515770.0,8358140.0,157630.0,204259812.0,0.77,14.46,6.58,0.14,2015-11-01 13:21:42.799461,2015-11-01 13:21:42.799461
24,25,bx,Brunei,5765.0,5265.0,500.0,429646.0,1.62,17.32,3.52,2.43,2015-11-01 13:21:47.136638,2015-11-01 13:21:47.136638
25,26,bu,Bulgaria,110879.0,108489.0,2390.0,7186893.0,0.58,8.92,14.44,0.29,2015-11-01 13:21:52.018824,2015-11-01 13:21:52.018824
26,27,uv,Burkina Faso,274200.0,273800.0,400.0,18931686.0,3.03,42.03,11.72,0.00,2015-11-01 13:21:56.976083,2015-11-01 13:21:56.976083
27,28,bm,Burma,676578.0,653508.0,23070.0,56320206.0,1.01,18.39,7.96,0.28,2015-11-01 13:22:03.329538,2015-11-01 13:22:03.329538
28,29,by,Burundi,27830.0,25680.0,2150.0,10742276.0,3.28,42.01,9.27,0.00,2015-11-01 13:22:08.382756,2015-11-01 13:22:08.382756
29,30,cb,Cambodia,181035.0,176515.0,4520.0,15708756.0,1.58,23.83,7.68,0.32,2015-11-01 13:22:16.286410,2015-11-01 13:22:16.286410
...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,195,zi,Zimbabwe,390757.0,386847.0,3910.0,14229541.0,2.21,32.26,10.13,0.00,2015-11-01 13:35:57.711444,2015-11-01 13:35:57.711444
195,196,tw,Taiwan,35980.0,32260.0,3720.0,23415126.0,0.23,8.47,7.11,0.89,2015-11-01 13:36:02.255373,2015-11-01 13:36:02.255373
203,204,hk,Hong Kong,1108.0,1073.0,35.0,7141106.0,0.38,9.23,7.07,1.68,2015-11-01 13:36:23.189516,2015-11-01 13:36:23.189516
204,205,mc,Macau,28.0,28.0,0.0,592731.0,0.80,8.88,4.22,3.37,2015-11-01 13:36:27.392999,2015-11-01 13:36:27.392999
205,206,fo,Faroe Islands,1393.0,1393.0,0.0,50196.0,0.51,13.77,8.71,0.00,2015-11-01 13:36:31.157109,2015-11-01 13:36:31.157109
208,209,fp,French Polynesia,4167.0,3827.0,340.0,282703.0,0.94,15.22,5.02,0.84,2015-11-01 13:36:40.733124,2015-11-01 13:36:40.733124
210,211,nc,New Caledonia,18575.0,18275.0,300.0,271615.0,1.38,15.33,5.52,4.01,2015-11-01 13:36:47.582833,2015-11-01 13:36:47.582833
213,214,sb,Saint Pierre and Miquelon,242.0,242.0,0.0,5657.0,1.08,7.42,9.72,8.49,2015-11-01 13:36:55.432885,2015-11-01 13:36:55.432885
214,215,wf,Wallis and Futuna,142.0,142.0,0.0,15613.0,0.33,13.45,5.06,5.06,2015-11-01 13:36:58.489862,2015-11-01 13:36:58.489862
215,216,aa,Aruba,180.0,180.0,0.0,112162.0,1.33,12.56,8.18,8.92,2015-11-01 13:37:02.407642,2015-11-01 13:37:02.407642
216,217,cc,Curacao,444.0,444.0,0.0,148406.0,0.43,13.80,8.20,1.40,2015-11-01 13:37:05.782750,2015-11-01 13:37:05.782750
217,218,sk,Sint Maarten,34.0,34.0,0.0,39689.0,1.51,13.00,4.51,6.63,2015-11-01 13:37:08.571949,2015-11-01 13:37:08.571949
225,226,av,Anguilla,91.0,91.0,0.0,16418.0,2.03,12.67,4.57,12.18,2015-11-01 13:37:30.034876,2015-11-01 13:37:30.034876
226,227,bd,Bermuda,54.0,54.0,0.0,70196.0,0.50,11.33,8.23,1.88,2015-11-01 13:37:33.894038,2015-11-01 13:37:33.894038
228,229,vi,British Virgin Islands,151.0,151.0,0.0,33454.0,2.32,10.91,4.99,17.28,2015-11-01 13:37:39.647840,2015-11-01 13:37:39.647840
229,230,cj,Cayman Islands,264.0,264.0,0.0,56092.0,2.10,12.11,5.53,14.40,2015-11-01 13:37:43.647884,2015-11-01 13:37:43.647884
232,233,gi,Gibraltar,6.0,6.0,0.0,29258.0,0.24,14.08,8.37,3.28,2015-11-01 13:37:51.980087,2015-11-01 13:37:51.980087
233,234,gk,Guernsey,78.0,78.0,0.0,66080.0,0.34,9.84,8.78,2.32,2015-11-01 13:37:55.085750,2015-11-01 13:37:55.085750
234,235,je,Jersey,116.0,116.0,0.0,97294.0,0.80,11.91,7.68,3.76,2015-11-01 13:37:58.442238,2015-11-01 13:37:58.442238
235,236,im,Isle of Man,572.0,572.0,0.0,87545.0,0.76,11.10,10.06,6.56,2015-11-01 13:38:01.914270,2015-11-01 13:38:01.914270
236,237,mh,Montserrat,102.0,102.0,0.0,5241.0,0.50,11.26,6.30,0.00,2015-11-01 13:38:05.670256,2015-11-01 13:38:05.670256
238,239,sh,"Saint Helena, Ascension, and Tristan da Cunha",308.0,122.0,0.0,7795.0,0.24,9.88,7.44,0.00,2015-11-01 13:38:11.767274,2015-11-01 13:38:11.767274
240,241,tk,Turks and Caicos Islands,948.0,948.0,0.0,50280.0,2.30,16.13,3.10,9.94,2015-11-01 13:38:17.164473,2015-11-01 13:38:17.164473
241,242,aq,American Samoa,199.0,199.0,0.0,54343.0,0.30,22.89,4.75,21.13,2015-11-01 13:38:20.926072,2015-11-01 13:38:20.926072
242,243,gq,Guam,544.0,544.0,0.0,161785.0,0.54,16.82,5.12,6.34,2015-11-01 13:38:24.699655,2015-11-01 13:38:24.699655
244,245,cq,Northern Mariana Islands,464.0,464.0,0.0,52344.0,2.18,18.32,3.71,7.16,2015-11-01 13:38:30.017480,2015-11-01 13:38:30.017480
245,246,rq,Puerto Rico,13791.0,8870.0,4921.0,3598357.0,0.60,10.86,8.67,8.15,2015-11-01 13:38:34.502065,2015-11-01 13:38:34.502065
246,247,vq,Virgin Islands,1910.0,346.0,1564.0,103574.0,0.59,10.31,8.54,7.67,2015-11-01 13:38:38.270075,2015-11-01 13:38:38.270075
250,251,gz,Gaza Strip,360.0,360.0,0.0,1869055.0,2.81,31.11,3.04,0.00,2015-11-01 13:38:48.049460,2015-11-01 13:38:48.049460
253,254,we,West Bank,5860.0,5640.0,220.0,2785366.0,1.95,22.99,3.50,0.00,2015-11-01 13:38:55.084643,2015-11-01 13:38:55.084643

In [4]:
def population_growth(initial_population,growth_rate):
    return initial_population * math.e **(growth_rate*35)

In [6]:
facts["35years_later"] = facts.apply(lambda x:population_growth(x["population"],x["population_growth"]),axis=1)
print(facts.sort_values(by="35years_later",ascending=False)[["name","35years_later"]].head(10))

             name  35years_later
161   South Sudan   1.534493e+68
105        Malawi   5.241296e+57
28        Burundi   7.728636e+56
181        Uganda   6.582465e+56
127         Niger   4.543303e+56
26   Burkina Faso   2.158336e+53
140         Qatar   1.014706e+53
108          Mali   3.359124e+52
79           Iraq   1.275733e+52
57       Ethiopia   8.444243e+51